apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: whohacks-ingress
spec:
  rules:
    - http:
        paths:
          - path: /jsonrpc
            backend: 
              serviceName: sfu
              servicePort: 7000
          - path: /grpc
            backend: 
              serviceName: sfu
              servicePort: 50051